version: '3.8'

services:
  eda_app:
    build:
      context: .
    ports:
      - 3000:3000
    env_file:
      - envs/.env.prod
    volumes:
      - ../:/home/node/eda_app
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    extra_hosts:
      - "host.docker.internal:15672"
    labels:
      filebeat_collector: true
    depends_on:
      - eda_db
  
  eda_db:
    image: postgres
    restart: always
    tty: true
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: eda
    volumes:
      - ../.docker/db/eda:/var/lib/postgresql/data