version: '3.8'

services:
  eda_app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./.docker/start.sh
    ports:
      - 3001:3000
    volumes:
      - ../:/home/node/eda_app
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      filebeat_collector: true
    depends_on:
      - eda_db
    networks:
      - app-network
    
  
  eda_db:
    image: postgres
    restart: always
    tty: true
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: eda
    volumes:
      - ../.docker/db/eda:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    external: true